name: Deploy SFTP

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: 31.97.162.177
          username: teste2
          password:  ${{ secrets.PASSWORD_ERP_SSH }}
          port: 22
          uploads: |
            ./ => ./htdocs/teste.nossafco.com.br/public
