name: Deploy SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: 31.97.162.177
          username: teste2
          password: o9ddEzis44MRge3wxj33
          port: 22
          uploads: |
            ./ => ./htdocs/teste.nossafco.com.br/public
